module Thesis.Everything where

import Thesis.Prelude.Category
import Thesis.Prelude.Category.Isomorphism
import Thesis.Prelude.Category.Isomorphism.Functor
import Thesis.Prelude.Category.Pullback
import Thesis.Prelude.Category.Pullback.Midpoint
import Thesis.Prelude.Category.Slice
import Thesis.Prelude.Category.Slice.Functor
import Thesis.Prelude.Category.Span
import Thesis.Prelude.Equality
import Thesis.Prelude.Function
import Thesis.Prelude.Function.Fam
import Thesis.Prelude.Function.Isomorphism
import Thesis.Prelude.Implication
import Thesis.Prelude.InverseImage
import Thesis.Prelude.Product
import Thesis.Refinement
import Thesis.Refinement.Category
import Thesis.Refinement.Isomorphism
import Thesis.Description
import Thesis.Description.HorizontalEquivalence
import Thesis.Ornament
import Thesis.Ornament.Algebraic
import Thesis.Ornament.Algebraic.FundamentalTheorems
import Thesis.Ornament.Algebraic.Fusion
import Thesis.Ornament.Category
import Thesis.Ornament.Equivalence
import Thesis.Ornament.Isomorphism
import Thesis.Ornament.ParallelComposition
import Thesis.Ornament.ParallelComposition.Pullback
import Thesis.Ornament.ParallelComposition.Swap
import Thesis.Ornament.RefinementSemantics
import Thesis.Ornament.SequentialComposition
import Thesis.Ornament.SequentialComposition.Swap
import Thesis.Relation
import Thesis.Relation.Division
import Thesis.Relation.Fold
import Thesis.Relation.GreedyTheorem
import Thesis.Relation.Hylomorphism
import Thesis.Relation.Minimum
import Thesis.Examples.Insertion
import Thesis.Examples.LeftistHeap
import Thesis.Examples.List
import Thesis.Examples.List.Sorted
import Thesis.Examples.List.Vec
import Thesis.Examples.Nat
import Thesis.Examples.Nat.TotalOrdering
